frr version 9.0
frr defaults traditional
hostname R1
log syslog informational
!
interface eth0
 description Internet
!
interface eth0
 description ISP-WAN
!
interface eth0
 description LAN-A
!
router ospf
 ospf router-id 1.1.1.1
 network 172.31.0.0/29 area 0
 network 172.20.10.0/24 area 0
 passive-interface eth0
 default-information originate always
!
ip route 0.0.0.0/0 172.30.0.254
!
line vty
!