frr version 9.0
frr defaults traditional
hostname R2
log syslog informational
!
interface eth0
 description ISP-WAN
!
interface eth1
 description LAN-B
!
router ospf
 ospf router-id 2.2.2.2
 network 172.31.0.0/29 area 0
 network 172.20.20.0/24 area 0
 passive-interface eth1
!
line vty
!
