config setup
    charondebug="ike 1, knl 1, cfg 0"
    uniqueids=no

conn branch
    auto=start
    keyexchange=ikev2
    authby=secret
    left=172.30.1.1
    leftsubnet=172.20.10.0/24,172.20.30.0/24
    right=172.30.1.2
    rightsubnet=172.20.20.0/24
    ike=aes256-sha2_256-modp2048!
    esp=aes256-sha2_256!
