vrrp_instance VI_LAN_A {
    state MASTER
    interface LAN_A_IF
    virtual_router_id 10
    priority 200
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        172.20.10.1/24
    }
}

vrrp_instance VI_DMZ {
    state MASTER
    interface DMZ_IF
    virtual_router_id 30
    priority 200
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        172.20.30.1/24
    }
}
